### ISSUE TITLE
Move group test issue

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup-pw/buttercup-core#39]
A very intermittent test failure:
```
ManagedGroupTests
✔ delete - testDeletesGroup
✔ delete - testThrowsForTrashGroup
✔ getAttribute - testGetsAttribute
✔ getEntries - testGetsEntries
✔ getID - testGetsID
✔ getTitle - testGetsTitle
✖ moveToGroup - testMovesToAnotherGroup

Assertion Message: Target group should have the new child group
AssertionError: Target group should have the new child group
    at Object.ok (/Users/pez/Git/buttercup-core/node_modules/nodeunit/lib/types.js:83:39)
    at Object.module.exports.moveToGroup.testMovesToAnotherGroup (/Users/pez/Git/buttercup-core/tests/ManagedGroupTests.js:104:9)
    at /Users/pez/Git/buttercup-core/node_modules/nodeunit/lib/core.js:232:20
    at /Users/pez/Git/buttercup-core/node_modules/nodeunit/deps/async.js:168:13
    at /Users/pez/Git/buttercup-core/node_modules/nodeunit/deps/async.js:131:25
    at /Users/pez/Git/buttercup-core/node_modules/nodeunit/deps/async.js:165:17
    at /Users/pez/Git/buttercup-core/node_modules/nodeunit/deps/async.js:463:34
    at Object.module.exports.setUp (/Users/pez/Git/buttercup-core/tests/ManagedGroupTests.js:35:7)
    at /Users/pez/Git/buttercup-core/node_modules/nodeunit/lib/core.js:260:35
    at /Users/pez/Git/buttercup-core/node_modules/nodeunit/deps/async.js:458:21
```

**Comment by perry-mitchell** [comment]
Now running `while npm test; do :; done` to test until failure

**Comment by perry-mitchell** [comment]
Example of a good move:
```
// before:
{
    "format": "buttercup/a",
    "groups": [
        {
            "id": "4e940351-3284-4ade-bab8-3d133c810d6f",
            "title": "Main",
            "attributes": {
                "testAttr": "testValue"
            },
            "entries": [
                {
                    "id": "f5ae5966-9636-4c06-838e-e0106163eda7",
                    "title": "My entry"
                }
            ]
        },
        {
            "id": "d380a864-023c-439f-9cef-9695341b010b",
            "title": "Mover"
        }
    ]
}
// after:
 {
    "format": "buttercup/a",
    "groups": [
        {
            "id": "4e940351-3284-4ade-bab8-3d133c810d6f",
            "title": "Main",
            "attributes": {
                "testAttr": "testValue"
            },
            "entries": [
                {
                    "id": "f5ae5966-9636-4c06-838e-e0106163eda7",
                    "title": "My entry"
                }
            ],
            "groups": [
                {
                    "id": "d380a864-023c-439f-9cef-9695341b010b",
                    "title": "Mover"
                }
            ]
        }
    ]
}
```

And the failing one:
```
// before:
{
    "format": "buttercup/a",
    "groups": [
        {
            "id": "0b9180ce-6e88-4f67-998c-7253d33d5dbc",
            "title": "Main",
            "attributes": {
                "testAttr": "testValue"
            },
            "entries": [
                {
                    "id": "07fa7359-041e-48e7-ad12-bd60c745ffce",
                    "title": "My entry"
                }
            ]
        },
        {
            "id": "eff60a23-31f5-4af4-a7e0-e8b392ea6204",
            "title": "Mover"
        }
    ]
}
// after:
{
    "format": "buttercup/a",
    "groups": [
        {
            "id": "0b9180ce-6e88-4f67-998c-7253d33d5dbc",
            "title": "Main",
            "attributes": {
                "testAttr": "testValue"
            },
            "entries": [
                {
                    "id": "07fa7359-041e-48e7-ad12-bd60c745ffce",
                    "title": "My entry"
                }
            ]
        },
        {
            "id": "eff60a23-31f5-4af4-a7e0-e8b392ea6204",
            "title": "Mover"
        }
    ]
}
```
