### ISSUE TITLE
npm test command failing to run

### ISSUE THREAD

**Issue by Jameskmonger** [buttercup-pw/buttercup-core#64]
When running `npm test`, I get the following error which prevents the tests from running at all:

```
> buttercup@0.16.0 test:nodeunit /home/james/Development/buttercup-core
> node node_modules/nodeunit/bin/nodeunit tests tests/integration tests/commands

module.js:339
    throw err;
    ^

Error: Cannot find module '__buttercup/classes/Archive.js'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at /home/james/Development/buttercup-core/source/module.js:7:18
    at Object.<anonymous> (/home/james/Development/buttercup-core/source/module.js:37:3)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)

npm ERR! Linux 3.19.0-51-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "test:nodeunit"
npm ERR! node v5.0.0
npm ERR! npm  v3.7.2
npm ERR! code ELIFECYCLE
npm ERR! buttercup@0.16.0 test:nodeunit: `node node_modules/nodeunit/bin/nodeunit tests tests/integration tests/commands`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the buttercup@0.16.0 test:nodeunit script 'node node_modules/nodeunit/bin/nodeunit tests tests/integration tests/commands'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the buttercup package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node_modules/nodeunit/bin/nodeunit tests tests/integration tests/commands
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs buttercup
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls buttercup
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/james/Development/buttercup-core/npm-debug.log
npm ERR! Test failed.  See above for more details.
```

**Comment by Jameskmonger** [comment]
This is a fresh clone, and I've run `sudo npm install` in the repository.

**Comment by Jameskmonger** [comment]
I've had a look in the `node_modules` folder and there doesn't appear to be a symlink to `__buttercup`.

**Comment by Jameskmonger** [comment]
After running `sudo node scripts/link.js`, the command `npm test` now runs correctly. Not sure when the `link` script is meant to be executed, @perry-mitchell ?

**Comment by Jameskmonger** [comment]
After looking in `package.json` and seeing that `link` is meant to be run with `npm install`, I tried running `sudo npm install` and got the following error:

```
james@JM-LAPTOP:~/Development/buttercup-core$ sudo npm install
npm WARN lifecycle buttercup@0.16.0~install: cannot run in wd %s %s (wd=%s) buttercup@0.16.0 node scripts/link.js /home/james/Development/buttercup-core
npm WARN enoent ENOENT: no such file or directory, open '/home/james/Development/buttercup-core/source/package.json'
```

**Comment by perry-mitchell** [comment]
Don't install using sudo - that'll for sure do weird things.

If you remove node modules, run `npm cache clean` and `sudo npm cache clean`, then run `npm install`, how does it look?

The reason for the error is that the source symlink is not being created..

**Comment by perry-mitchell** [comment]
Have you had this issue again @Jameskmonger ? If not, perhaps we could close it.

In general local packages should not be sudo-installed, but the npm link may just require a cache-clean and a reinstall.

**Comment by Jameskmonger** [comment]
I haven't had the same error, but I haven't done a fresh install since then. I'll close this and reopen it if it happens again.
